name: Retrieve data and create figures

on:
  schedule:
    - cron: '00 17 * * *'
  workflow_dispatch:

jobs:
  generate-and-commit-csv:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install requests bs4 numpy pandas pyarrow

      - name: Retrieve data and create figures
        run: python main.py

      - name: Commit and push
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/profiles.parquet data/station.parquet app/data
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Retrieve data and create figures"
          git push
